import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <main>{children}</main>
        <div className="flex justify-center">
        <footer className="absolute bottom-0 text-nyanza">Copyright © 2024 Juan Ignacio Leiva</footer>
        </div>
      </body>
    </html>
  );
}
